### PR TITLE
rename settings folder

### PR DESCRIPTION
**Pull request by vidok**

### CODE REVIEW

**Comment by vidok** [comment]
Is this project supported?

**Comment by rposborne** [comment]
+1

**Comment by jbender** [comment]
@skord this will solve #5 (and #6 since it's a dupe) and make your package usable for the upcoming `1.0` release. Please give it a look.

**Comment by jipiboily** [comment]
@skord it seems like this was not released? Anything we can do to help?

**Comment by skord** [comment]
@jipiboily correct, I'm going to try and hammer this out today. To say that I've been busy is an understatement. Thanks for the offer!

**Comment by i8ramin** [comment]
Until a new version is released, you can get rid of the warning by doing this (worked for me at least):

```
mv ~/.atom/packages/ruby-slim/scoped-properties ~/.atom/packages/ruby-slim/settings
```

**Comment by skord** [comment]
Sorry to be a total dick about the release of this, I've just gotten back from my first vacation in 10 years and am just catching up on life. If I can transfer this to someone who has more time, I'm game.

**Comment by vidok** [comment]
I'm ready to do it

**Pull request merged**
